### PR TITLE
readme: Update languages available

### PR DESCRIPTION
**Pull request by ivanhercaz**
Hi @wlemuel!

I use this client in Vim. It is very useful if you don't want to go out of Vim. However, the languages availability shown in the README is outdated, so this PR introduce two changes:

  1. Update the list to the current date.
  2. Order the list by the language code (`option` column).

### CODE REVIEW

**Comment by wlemuel** [comment]
Thanks ~

**Comment by bl-ue** [comment]
@ivanhercaz where did you get this list from?  From the `pages.*` available in the [main repo](https://github.com/tldr-pages/tldr)?  If so, this repo could use an update again.

**Comment by wlemuel** [comment]
@bl-ue Yes, it is from the `pages.*` available in the [main repo](https://github.com/tldr-pages/tldr), excepting the fallback language (English).
I have updated the supported language list to the latest.

**Comment by bl-ue** [comment]
Thank you @wlemuel for your quick response (I didn't even expect you to see this 😄 )!

**Comment by bl-ue** [comment]
Over time we have been collecting quite a few languages :D

**Comment by wlemuel** [comment]
@bl-ue 

I'd be glad to receive patches, comments and your considered criticism.
Have fun with `vim-tldr`!

**Pull request merged**
